modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20First%20Join%20Message"
logoFile="icon.png"

[[mods]]
modId="firstjoinmessage"
version="3.4"
displayName="First Join Message"
displayURL="https://serilum.com/mod/first-join-message"
authors="Rick South"
description='''Sends players who join a world for the first time a configurable message.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Jack, Kreezxil, Michael W. S., Mir3JonCZ, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.firstjoinmessage]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.firstjoinmessage]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"